/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace A2AJobEscrow {
  export type JobStruct = {
    creatorAgentId: BigNumberish;
    providerAgentId: BigNumberish;
    creatorWallet: AddressLike;
    providerWallet: AddressLike;
    requirementsHash: BytesLike;
    agreementHash: BytesLike;
    deliverableHash: BytesLike;
    reportHash: BytesLike;
    budgetMin: BigNumberish;
    budgetMax: BigNumberish;
    agreedPrice: BigNumberish;
    createdAt: BigNumberish;
    fundedAt: BigNumberish;
    executionDeadline: BigNumberish;
    executionWindow: BigNumberish;
    commissionBps: BigNumberish;
    status: BigNumberish;
  };

  export type JobStructOutput = [
    creatorAgentId: bigint,
    providerAgentId: bigint,
    creatorWallet: string,
    providerWallet: string,
    requirementsHash: string,
    agreementHash: string,
    deliverableHash: string,
    reportHash: string,
    budgetMin: bigint,
    budgetMax: bigint,
    agreedPrice: bigint,
    createdAt: bigint,
    fundedAt: bigint,
    executionDeadline: bigint,
    executionWindow: bigint,
    commissionBps: bigint,
    status: bigint
  ] & {
    creatorAgentId: bigint;
    providerAgentId: bigint;
    creatorWallet: string;
    providerWallet: string;
    requirementsHash: string;
    agreementHash: string;
    deliverableHash: string;
    reportHash: string;
    budgetMin: bigint;
    budgetMax: bigint;
    agreedPrice: bigint;
    createdAt: bigint;
    fundedAt: bigint;
    executionDeadline: bigint;
    executionWindow: bigint;
    commissionBps: bigint;
    status: bigint;
  };

  export type AgreementStruct = {
    jobId: BytesLike;
    creatorAgentId: BigNumberish;
    providerAgentId: BigNumberish;
    providerWallet: AddressLike;
    agreedPrice: BigNumberish;
    requirementsHash: BytesLike;
    executionWindow: BigNumberish;
    transcriptHash: BytesLike;
    expiry: BigNumberish;
  };

  export type AgreementStructOutput = [
    jobId: string,
    creatorAgentId: bigint,
    providerAgentId: bigint,
    providerWallet: string,
    agreedPrice: bigint,
    requirementsHash: string,
    executionWindow: bigint,
    transcriptHash: string,
    expiry: bigint
  ] & {
    jobId: string;
    creatorAgentId: bigint;
    providerAgentId: bigint;
    providerWallet: string;
    agreedPrice: bigint;
    requirementsHash: string;
    executionWindow: bigint;
    transcriptHash: string;
    expiry: bigint;
  };
}

export interface A2AJobEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGREEMENT_TYPEHASH"
      | "ARBITER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_COMMISSION_BPS"
      | "MAX_EXECUTION_WINDOW"
      | "MIN_EXECUTION_WINDOW"
      | "RELAYER_ROLE"
      | "VERIFICATION_GRACE"
      | "VERIFIER_ROLE"
      | "cancelBeforeFunding"
      | "commissionBps"
      | "domainSeparator"
      | "eip712Domain"
      | "exists"
      | "getJob"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hashAgreement"
      | "jobStatus"
      | "pause"
      | "paused"
      | "postJob"
      | "refundClaimable"
      | "renounceRole"
      | "revokeRole"
      | "setCommissionBps"
      | "setTreasury"
      | "supportsInterface"
      | "treasury"
      | "unpause"
      | "usdc"
      | "verifyAgreement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommissionBpsUpdated"
      | "DeliverableSubmitted"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EIP712DomainChanged"
      | "JobCancelled"
      | "JobExecuting"
      | "JobFunded"
      | "JobPosted"
      | "JobRefunded"
      | "JobSettled"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AGREEMENT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COMMISSION_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXECUTION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EXECUTION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_GRACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBeforeFunding",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commissionBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "exists", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getJob", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashAgreement",
    values: [A2AJobEscrow.AgreementStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "jobStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "refundClaimable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommissionBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAgreement",
    values: [
      A2AJobEscrow.AgreementStruct,
      AddressLike,
      BytesLike,
      AddressLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "AGREEMENT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COMMISSION_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXECUTION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EXECUTION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_GRACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBeforeFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commissionBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommissionBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgreement",
    data: BytesLike
  ): Result;
}

export namespace CommissionBpsUpdatedEvent {
  export type InputTuple = [newBps: BigNumberish];
  export type OutputTuple = [newBps: bigint];
  export interface OutputObject {
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliverableSubmittedEvent {
  export type InputTuple = [jobId: BytesLike, deliverableHash: BytesLike];
  export type OutputTuple = [jobId: string, deliverableHash: string];
  export interface OutputObject {
    jobId: string;
    deliverableHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [jobId: BytesLike, raisedBy: AddressLike];
  export type OutputTuple = [jobId: string, raisedBy: string];
  export interface OutputObject {
    jobId: string;
    raisedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    toProvider: BigNumberish,
    toCreator: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    toProvider: bigint,
    toCreator: bigint
  ];
  export interface OutputObject {
    jobId: string;
    toProvider: bigint;
    toCreator: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BytesLike];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobExecutingEvent {
  export type InputTuple = [jobId: BytesLike];
  export type OutputTuple = [jobId: string];
  export interface OutputObject {
    jobId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFundedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    providerAgentId: BigNumberish,
    providerWallet: AddressLike,
    agreedPrice: BigNumberish,
    agreementHash: BytesLike,
    executionDeadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    providerAgentId: bigint,
    providerWallet: string,
    agreedPrice: bigint,
    agreementHash: string,
    executionDeadline: bigint
  ];
  export interface OutputObject {
    jobId: string;
    providerAgentId: bigint;
    providerWallet: string;
    agreedPrice: bigint;
    agreementHash: string;
    executionDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    creatorAgentId: BigNumberish,
    creatorWallet: AddressLike,
    requirementsHash: BytesLike,
    budgetMin: BigNumberish,
    budgetMax: BigNumberish,
    executionWindow: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    creatorAgentId: bigint,
    creatorWallet: string,
    requirementsHash: string,
    budgetMin: bigint,
    budgetMax: bigint,
    executionWindow: bigint
  ];
  export interface OutputObject {
    jobId: string;
    creatorAgentId: bigint;
    creatorWallet: string;
    requirementsHash: string;
    budgetMin: bigint;
    budgetMax: bigint;
    executionWindow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRefundedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    creatorWallet: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    jobId: string,
    creatorWallet: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    jobId: string;
    creatorWallet: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSettledEvent {
  export type InputTuple = [
    jobId: BytesLike,
    providerWallet: AddressLike,
    payout: BigNumberish,
    commission: BigNumberish,
    reportHash: BytesLike
  ];
  export type OutputTuple = [
    jobId: string,
    providerWallet: string,
    payout: bigint,
    commission: bigint,
    reportHash: string
  ];
  export interface OutputObject {
    jobId: string;
    providerWallet: string;
    payout: bigint;
    commission: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface A2AJobEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): A2AJobEscrow;
  waitForDeployment(): Promise<this>;

  interface: A2AJobEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGREEMENT_TYPEHASH: TypedContractMethod<[], [string], "view">;

  ARBITER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_COMMISSION_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_EXECUTION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MIN_EXECUTION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFICATION_GRACE: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  cancelBeforeFunding: TypedContractMethod<
    [jobId: BytesLike],
    [void],
    "nonpayable"
  >;

  commissionBps: TypedContractMethod<[], [bigint], "view">;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  exists: TypedContractMethod<[jobId: BytesLike], [boolean], "view">;

  getJob: TypedContractMethod<
    [jobId: BytesLike],
    [A2AJobEscrow.JobStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashAgreement: TypedContractMethod<
    [agreement: A2AJobEscrow.AgreementStruct],
    [string],
    "view"
  >;

  jobStatus: TypedContractMethod<[jobId: BytesLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  postJob: TypedContractMethod<
    [
      jobId: BytesLike,
      creatorAgentId: BigNumberish,
      creatorWallet: AddressLike,
      requirementsHash: BytesLike,
      budgetMin: BigNumberish,
      budgetMax: BigNumberish,
      executionWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  refundClaimable: TypedContractMethod<[jobId: BytesLike], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCommissionBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  verifyAgreement: TypedContractMethod<
    [
      agreement: A2AJobEscrow.AgreementStruct,
      creatorSigner: AddressLike,
      creatorSig: BytesLike,
      providerSigner: AddressLike,
      providerSig: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGREEMENT_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ARBITER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_COMMISSION_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXECUTION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EXECUTION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_GRACE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelBeforeFunding"
  ): TypedContractMethod<[jobId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commissionBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [A2AJobEscrow.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashAgreement"
  ): TypedContractMethod<
    [agreement: A2AJobEscrow.AgreementStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobStatus"
  ): TypedContractMethod<[jobId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      jobId: BytesLike,
      creatorAgentId: BigNumberish,
      creatorWallet: AddressLike,
      requirementsHash: BytesLike,
      budgetMin: BigNumberish,
      budgetMax: BigNumberish,
      executionWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refundClaimable"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCommissionBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAgreement"
  ): TypedContractMethod<
    [
      agreement: A2AJobEscrow.AgreementStruct,
      creatorSigner: AddressLike,
      creatorSig: BytesLike,
      providerSigner: AddressLike,
      providerSig: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "CommissionBpsUpdated"
  ): TypedContractEvent<
    CommissionBpsUpdatedEvent.InputTuple,
    CommissionBpsUpdatedEvent.OutputTuple,
    CommissionBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DeliverableSubmitted"
  ): TypedContractEvent<
    DeliverableSubmittedEvent.InputTuple,
    DeliverableSubmittedEvent.OutputTuple,
    DeliverableSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobExecuting"
  ): TypedContractEvent<
    JobExecutingEvent.InputTuple,
    JobExecutingEvent.OutputTuple,
    JobExecutingEvent.OutputObject
  >;
  getEvent(
    key: "JobFunded"
  ): TypedContractEvent<
    JobFundedEvent.InputTuple,
    JobFundedEvent.OutputTuple,
    JobFundedEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "JobRefunded"
  ): TypedContractEvent<
    JobRefundedEvent.InputTuple,
    JobRefundedEvent.OutputTuple,
    JobRefundedEvent.OutputObject
  >;
  getEvent(
    key: "JobSettled"
  ): TypedContractEvent<
    JobSettledEvent.InputTuple,
    JobSettledEvent.OutputTuple,
    JobSettledEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CommissionBpsUpdated(uint16)": TypedContractEvent<
      CommissionBpsUpdatedEvent.InputTuple,
      CommissionBpsUpdatedEvent.OutputTuple,
      CommissionBpsUpdatedEvent.OutputObject
    >;
    CommissionBpsUpdated: TypedContractEvent<
      CommissionBpsUpdatedEvent.InputTuple,
      CommissionBpsUpdatedEvent.OutputTuple,
      CommissionBpsUpdatedEvent.OutputObject
    >;

    "DeliverableSubmitted(bytes32,bytes32)": TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;
    DeliverableSubmitted: TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;

    "DisputeRaised(bytes32,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint128,uint128)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "JobCancelled(bytes32)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobExecuting(bytes32)": TypedContractEvent<
      JobExecutingEvent.InputTuple,
      JobExecutingEvent.OutputTuple,
      JobExecutingEvent.OutputObject
    >;
    JobExecuting: TypedContractEvent<
      JobExecutingEvent.InputTuple,
      JobExecutingEvent.OutputTuple,
      JobExecutingEvent.OutputObject
    >;

    "JobFunded(bytes32,uint256,address,uint128,bytes32,uint64)": TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;
    JobFunded: TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;

    "JobPosted(bytes32,uint256,address,bytes32,uint128,uint128,uint32)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "JobRefunded(bytes32,address,uint128,string)": TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;
    JobRefunded: TypedContractEvent<
      JobRefundedEvent.InputTuple,
      JobRefundedEvent.OutputTuple,
      JobRefundedEvent.OutputObject
    >;

    "JobSettled(bytes32,address,uint128,uint128,bytes32)": TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;
    JobSettled: TypedContractEvent<
      JobSettledEvent.InputTuple,
      JobSettledEvent.OutputTuple,
      JobSettledEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
