packages:
  - 'apps/*'
  - 'services/*'
  - 'workers/*'
  - 'packages/*'
  - 'contracts/evm'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@reown/appkit'
  - bigint-buffer
  - bufferutil
  - es5-ext
  - esbuild
  - keccak
  - prisma
  - secp256k1
  - unrs-resolver
  - utf-8-validate
