/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArenaDepositVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "dailyCapPerUser"
      | "depositFeeBps"
      | "depositNative"
      | "depositNonce"
      | "depositUSDC"
      | "depositUSDT"
      | "emergencyWithdraw"
      | "feeCollector"
      | "maxDepositNative"
      | "maxDepositStable"
      | "minDepositNative"
      | "minDepositStable"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "processRedemption"
      | "renounceOwnership"
      | "setDailyCap"
      | "setDepositFee"
      | "setDepositLimitsNative"
      | "setDepositLimitsStable"
      | "setFeeCollector"
      | "transferOwnership"
      | "unpause"
      | "usdc"
      | "usdt"
      | "userDailyDeposited"
      | "userLastDepositDay"
      | "vaultBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyCapUpdated"
      | "DepositQueued"
      | "FeeUpdated"
      | "MinMaxNativeUpdated"
      | "MinMaxStableUpdated"
      | "NativeReceived"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "RedemptionProcessed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyCapPerUser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositUSDC",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositUSDT",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDepositNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDepositStable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDepositNative",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minDepositStable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processRedemption",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositLimitsNative",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositLimitsStable",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDailyDeposited",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLastDepositDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyCapPerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDepositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDepositStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minDepositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minDepositStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositLimitsNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositLimitsStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDailyDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLastDepositDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultBalance",
    data: BytesLike
  ): Result;
}

export namespace DailyCapUpdatedEvent {
  export type InputTuple = [newCap: BigNumberish];
  export type OutputTuple = [newCap: bigint];
  export interface OutputObject {
    newCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositQueuedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    depositor: AddressLike,
    solanaRecipient: BytesLike,
    asset: BigNumberish,
    amount: BigNumberish,
    fee: BigNumberish,
    chain: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    depositor: string,
    solanaRecipient: string,
    asset: bigint,
    amount: bigint,
    fee: bigint,
    chain: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    depositor: string;
    solanaRecipient: string;
    asset: bigint;
    amount: bigint;
    fee: bigint;
    chain: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinMaxNativeUpdatedEvent {
  export type InputTuple = [min: BigNumberish, max: BigNumberish];
  export type OutputTuple = [min: bigint, max: bigint];
  export interface OutputObject {
    min: bigint;
    max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinMaxStableUpdatedEvent {
  export type InputTuple = [min: BigNumberish, max: BigNumberish];
  export type OutputTuple = [min: bigint, max: bigint];
  export interface OutputObject {
    min: bigint;
    max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeReceivedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionProcessedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    usdcAmount: BigNumberish,
    solanaProof: BytesLike
  ];
  export type OutputTuple = [
    recipient: string,
    usdcAmount: bigint,
    solanaProof: string
  ];
  export interface OutputObject {
    recipient: string;
    usdcAmount: bigint;
    solanaProof: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArenaDepositVault extends BaseContract {
  connect(runner?: ContractRunner | null): ArenaDepositVault;
  waitForDeployment(): Promise<this>;

  interface: ArenaDepositVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  dailyCapPerUser: TypedContractMethod<[], [bigint], "view">;

  depositFeeBps: TypedContractMethod<[], [bigint], "view">;

  depositNative: TypedContractMethod<
    [solanaRecipient: BytesLike],
    [void],
    "payable"
  >;

  depositNonce: TypedContractMethod<[], [bigint], "view">;

  depositUSDC: TypedContractMethod<
    [amount: BigNumberish, solanaRecipient: BytesLike],
    [void],
    "nonpayable"
  >;

  depositUSDT: TypedContractMethod<
    [amount: BigNumberish, solanaRecipient: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  maxDepositNative: TypedContractMethod<[], [bigint], "view">;

  maxDepositStable: TypedContractMethod<[], [bigint], "view">;

  minDepositNative: TypedContractMethod<[], [bigint], "view">;

  minDepositStable: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  processRedemption: TypedContractMethod<
    [recipient: AddressLike, usdcAmount: BigNumberish, solanaProof: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDailyCap: TypedContractMethod<[_cap: BigNumberish], [void], "nonpayable">;

  setDepositFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositLimitsNative: TypedContractMethod<
    [_min: BigNumberish, _max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositLimitsStable: TypedContractMethod<
    [_min: BigNumberish, _max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeCollector: TypedContractMethod<
    [_collector: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  userDailyDeposited: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userLastDepositDay: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  vaultBalance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        usdcBal: bigint;
        usdtBal: bigint;
        nativeBal: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dailyCapPerUser"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<[solanaRecipient: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "depositNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositUSDC"
  ): TypedContractMethod<
    [amount: BigNumberish, solanaRecipient: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositUSDT"
  ): TypedContractMethod<
    [amount: BigNumberish, solanaRecipient: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxDepositNative"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxDepositStable"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDepositNative"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minDepositStable"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processRedemption"
  ): TypedContractMethod<
    [recipient: AddressLike, usdcAmount: BigNumberish, solanaProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyCap"
  ): TypedContractMethod<[_cap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositLimitsNative"
  ): TypedContractMethod<
    [_min: BigNumberish, _max: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDepositLimitsStable"
  ): TypedContractMethod<
    [_min: BigNumberish, _max: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_collector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userDailyDeposited"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userLastDepositDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vaultBalance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        usdcBal: bigint;
        usdtBal: bigint;
        nativeBal: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DailyCapUpdated"
  ): TypedContractEvent<
    DailyCapUpdatedEvent.InputTuple,
    DailyCapUpdatedEvent.OutputTuple,
    DailyCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositQueued"
  ): TypedContractEvent<
    DepositQueuedEvent.InputTuple,
    DepositQueuedEvent.OutputTuple,
    DepositQueuedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinMaxNativeUpdated"
  ): TypedContractEvent<
    MinMaxNativeUpdatedEvent.InputTuple,
    MinMaxNativeUpdatedEvent.OutputTuple,
    MinMaxNativeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinMaxStableUpdated"
  ): TypedContractEvent<
    MinMaxStableUpdatedEvent.InputTuple,
    MinMaxStableUpdatedEvent.OutputTuple,
    MinMaxStableUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NativeReceived"
  ): TypedContractEvent<
    NativeReceivedEvent.InputTuple,
    NativeReceivedEvent.OutputTuple,
    NativeReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionProcessed"
  ): TypedContractEvent<
    RedemptionProcessedEvent.InputTuple,
    RedemptionProcessedEvent.OutputTuple,
    RedemptionProcessedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DailyCapUpdated(uint256)": TypedContractEvent<
      DailyCapUpdatedEvent.InputTuple,
      DailyCapUpdatedEvent.OutputTuple,
      DailyCapUpdatedEvent.OutputObject
    >;
    DailyCapUpdated: TypedContractEvent<
      DailyCapUpdatedEvent.InputTuple,
      DailyCapUpdatedEvent.OutputTuple,
      DailyCapUpdatedEvent.OutputObject
    >;

    "DepositQueued(uint256,address,bytes32,uint8,uint256,uint256,uint256)": TypedContractEvent<
      DepositQueuedEvent.InputTuple,
      DepositQueuedEvent.OutputTuple,
      DepositQueuedEvent.OutputObject
    >;
    DepositQueued: TypedContractEvent<
      DepositQueuedEvent.InputTuple,
      DepositQueuedEvent.OutputTuple,
      DepositQueuedEvent.OutputObject
    >;

    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "MinMaxNativeUpdated(uint256,uint256)": TypedContractEvent<
      MinMaxNativeUpdatedEvent.InputTuple,
      MinMaxNativeUpdatedEvent.OutputTuple,
      MinMaxNativeUpdatedEvent.OutputObject
    >;
    MinMaxNativeUpdated: TypedContractEvent<
      MinMaxNativeUpdatedEvent.InputTuple,
      MinMaxNativeUpdatedEvent.OutputTuple,
      MinMaxNativeUpdatedEvent.OutputObject
    >;

    "MinMaxStableUpdated(uint256,uint256)": TypedContractEvent<
      MinMaxStableUpdatedEvent.InputTuple,
      MinMaxStableUpdatedEvent.OutputTuple,
      MinMaxStableUpdatedEvent.OutputObject
    >;
    MinMaxStableUpdated: TypedContractEvent<
      MinMaxStableUpdatedEvent.InputTuple,
      MinMaxStableUpdatedEvent.OutputTuple,
      MinMaxStableUpdatedEvent.OutputObject
    >;

    "NativeReceived(address,uint256)": TypedContractEvent<
      NativeReceivedEvent.InputTuple,
      NativeReceivedEvent.OutputTuple,
      NativeReceivedEvent.OutputObject
    >;
    NativeReceived: TypedContractEvent<
      NativeReceivedEvent.InputTuple,
      NativeReceivedEvent.OutputTuple,
      NativeReceivedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RedemptionProcessed(address,uint256,bytes32)": TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;
    RedemptionProcessed: TypedContractEvent<
      RedemptionProcessedEvent.InputTuple,
      RedemptionProcessedEvent.OutputTuple,
      RedemptionProcessedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
