/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aiArenaInftSol from "./AIArenaINFT.sol";
export type { aiArenaInftSol };
export type { AgentRegistry } from "./AgentRegistry";
export type { ArenaDepositVault } from "./ArenaDepositVault";
export type { ModuleMarketplace } from "./ModuleMarketplace";
