/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ModuleMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hasPurchased"
      | "listModule"
      | "modules"
      | "owner"
      | "purchaseModule"
      | "purchases"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ModuleListed"
      | "ModulePurchased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listModule",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "modules", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "purchases",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listModule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "modules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ModuleListedEvent {
  export type InputTuple = [
    moduleId: string,
    creator: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [moduleId: string, creator: string, price: bigint];
  export interface OutputObject {
    moduleId: string;
    creator: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModulePurchasedEvent {
  export type InputTuple = [moduleId: string, buyer: AddressLike];
  export type OutputTuple = [moduleId: string, buyer: string];
  export interface OutputObject {
    moduleId: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ModuleMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): ModuleMarketplace;
  waitForDeployment(): Promise<this>;

  interface: ModuleMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasPurchased: TypedContractMethod<
    [buyer: AddressLike, moduleId: string],
    [boolean],
    "view"
  >;

  listModule: TypedContractMethod<
    [
      moduleId: string,
      name: string,
      description: string,
      ipfsHash: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  modules: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        moduleId: string;
        name: string;
        description: string;
        ipfsHash: string;
        creator: string;
        price: bigint;
        purchaseCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseModule: TypedContractMethod<[moduleId: string], [void], "payable">;

  purchases: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<
    [buyer: AddressLike, moduleId: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listModule"
  ): TypedContractMethod<
    [
      moduleId: string,
      name: string,
      description: string,
      ipfsHash: string,
      price: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "modules"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        moduleId: string;
        name: string;
        description: string;
        ipfsHash: string;
        creator: string;
        price: bigint;
        purchaseCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseModule"
  ): TypedContractMethod<[moduleId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "purchases"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ModuleListed"
  ): TypedContractEvent<
    ModuleListedEvent.InputTuple,
    ModuleListedEvent.OutputTuple,
    ModuleListedEvent.OutputObject
  >;
  getEvent(
    key: "ModulePurchased"
  ): TypedContractEvent<
    ModulePurchasedEvent.InputTuple,
    ModulePurchasedEvent.OutputTuple,
    ModulePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ModuleListed(string,address,uint256)": TypedContractEvent<
      ModuleListedEvent.InputTuple,
      ModuleListedEvent.OutputTuple,
      ModuleListedEvent.OutputObject
    >;
    ModuleListed: TypedContractEvent<
      ModuleListedEvent.InputTuple,
      ModuleListedEvent.OutputTuple,
      ModuleListedEvent.OutputObject
    >;

    "ModulePurchased(string,address)": TypedContractEvent<
      ModulePurchasedEvent.InputTuple,
      ModulePurchasedEvent.OutputTuple,
      ModulePurchasedEvent.OutputObject
    >;
    ModulePurchased: TypedContractEvent<
      ModulePurchasedEvent.InputTuple,
      ModulePurchasedEvent.OutputTuple,
      ModulePurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
