[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow_vault  = "29zNbzvFbbmJ9BpzS6vS1Rm825kG4GUnwL2QdfusztsR"
tournament    = "31xMWgFzecP9FyXKxNEs6SKkSsB5PU4BY3whFeF6thTY"
agent_wallet  = "Dwksja1neBrS4Y2hntN2evkvpYp3Rw5QYQ1XUW8Po57H"
staking       = "C2imVK4kCxVSDs4FG9N3fXG6k45ueJARbVzbKy6A7kF8"

[programs.mainnet]
escrow_vault  = "29zNbzvFbbmJ9BpzS6vS1Rm825kG4GUnwL2QdfusztsR"
tournament    = "31xMWgFzecP9FyXKxNEs6SKkSsB5PU4BY3whFeF6thTY"
agent_wallet  = "Dwksja1neBrS4Y2hntN2evkvpYp3Rw5QYQ1XUW8Po57H"
staking       = "C2imVK4kCxVSDs4FG9N3fXG6k45ueJARbVzbKy6A7kF8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "escrow-vault",
  "tournament",
  "agent-wallet",
  "staking"
]
