/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AIArenaINFT {
  export type AgentTraitsStruct = {
    aggression: BigNumberish;
    patience: BigNumberish;
    adaptability: BigNumberish;
    riskTolerance: BigNumberish;
    precision: BigNumberish;
    endurance: BigNumberish;
    creativity: BigNumberish;
    teamwork: BigNumberish;
  };

  export type AgentTraitsStructOutput = [
    aggression: bigint,
    patience: bigint,
    adaptability: bigint,
    riskTolerance: bigint,
    precision: bigint,
    endurance: bigint,
    creativity: bigint,
    teamwork: bigint
  ] & {
    aggression: bigint;
    patience: bigint;
    adaptability: bigint;
    riskTolerance: bigint;
    precision: bigint;
    endurance: bigint;
    creativity: bigint;
    teamwork: bigint;
  };

  export type AgentMetadataStruct = {
    agentId: string;
    clan: string;
    archetype: string;
    evolutionStage: BigNumberish;
    wins: BigNumberish;
    losses: BigNumberish;
    draws: BigNumberish;
    totalBattles: BigNumberish;
    memoryRootHash: BytesLike;
    modelRootHash: string;
    genesisRootHash: string;
    encryptedMetadataHash: BytesLike;
    sealedKey: BytesLike;
    mintedAt: BigNumberish;
    lastEvolvedAt: BigNumberish;
    lastBattleAt: BigNumberish;
    lastTrainingAt: BigNumberish;
    traits: AIArenaINFT.AgentTraitsStruct;
  };

  export type AgentMetadataStructOutput = [
    agentId: string,
    clan: string,
    archetype: string,
    evolutionStage: bigint,
    wins: bigint,
    losses: bigint,
    draws: bigint,
    totalBattles: bigint,
    memoryRootHash: string,
    modelRootHash: string,
    genesisRootHash: string,
    encryptedMetadataHash: string,
    sealedKey: string,
    mintedAt: bigint,
    lastEvolvedAt: bigint,
    lastBattleAt: bigint,
    lastTrainingAt: bigint,
    traits: AIArenaINFT.AgentTraitsStructOutput
  ] & {
    agentId: string;
    clan: string;
    archetype: string;
    evolutionStage: bigint;
    wins: bigint;
    losses: bigint;
    draws: bigint;
    totalBattles: bigint;
    memoryRootHash: string;
    modelRootHash: string;
    genesisRootHash: string;
    encryptedMetadataHash: string;
    sealedKey: string;
    mintedAt: bigint;
    lastEvolvedAt: bigint;
    lastBattleAt: bigint;
    lastTrainingAt: bigint;
    traits: AIArenaINFT.AgentTraitsStructOutput;
  };
}

export interface AIArenaINFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CLONES"
      | "MAX_SUPPLY"
      | "agentIdToTokenId"
      | "agentMetadata"
      | "approve"
      | "authorisedOperators"
      | "authorizeUsage"
      | "balanceOf"
      | "clone"
      | "cloneCount"
      | "cloneParent"
      | "evolveAgent"
      | "getAgentByAgentId"
      | "getApproved"
      | "getEvolutionStage"
      | "getTraits"
      | "hasValidUsage"
      | "isApprovedForAll"
      | "mintAgent"
      | "name"
      | "oracle"
      | "owner"
      | "ownerOf"
      | "recordBattleResult"
      | "renounceOwnership"
      | "revokeUsage"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setOperator"
      | "setOracle"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "updateEncryptedMetadata"
      | "updateMemoryRoot"
      | "updateModelVersion"
      | "usagePermissions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentCloned"
      | "AgentEvolved"
      | "AgentMinted"
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "BattleResultRecorded"
      | "MemoryRootUpdated"
      | "MetadataUpdate"
      | "MetadataUpdated"
      | "ModelVersionUpdated"
      | "OracleUpdated"
      | "OwnershipTransferred"
      | "TraitsUpdated"
      | "Transfer"
      | "UsageAuthorized"
      | "UsageRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CLONES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentIdToTokenId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "agentMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorisedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeUsage",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clone",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cloneCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cloneParent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evolveAgent",
    values: [BigNumberish, AIArenaINFT.AgentTraitsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByAgentId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvolutionStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidUsage",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAgent",
    values: [
      AddressLike,
      string,
      string,
      string,
      AIArenaINFT.AgentTraitsStruct,
      BytesLike,
      BytesLike,
      string,
      string
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordBattleResult",
    values: [BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeUsage",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEncryptedMetadata",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMemoryRoot",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateModelVersion",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usagePermissions",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_CLONES", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentIdToTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorisedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cloneCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cloneParent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evolveAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByAgentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvolutionStage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTraits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasValidUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordBattleResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEncryptedMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMemoryRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateModelVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usagePermissions",
    data: BytesLike
  ): Result;
}

export namespace AgentClonedEvent {
  export type InputTuple = [
    parentId: BigNumberish,
    cloneId: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [parentId: bigint, cloneId: bigint, to: string];
  export interface OutputObject {
    parentId: bigint;
    cloneId: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentEvolvedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    fromStage: BigNumberish,
    toStage: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    fromStage: bigint,
    toStage: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    fromStage: bigint;
    toStage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    agentId: string,
    owner: AddressLike,
    clan: string
  ];
  export type OutputTuple = [
    tokenId: bigint,
    agentId: string,
    owner: string,
    clan: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    agentId: string;
    owner: string;
    clan: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleResultRecordedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    won: boolean,
    totalBattles: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    won: boolean,
    totalBattles: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    won: boolean;
    totalBattles: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemoryRootUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, memoryRoot: BytesLike];
  export type OutputTuple = [tokenId: bigint, memoryRoot: string];
  export interface OutputObject {
    tokenId: bigint;
    memoryRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, metadataHash: BytesLike];
  export type OutputTuple = [tokenId: bigint, metadataHash: string];
  export interface OutputObject {
    tokenId: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModelVersionUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, modelRootHash: string];
  export type OutputTuple = [tokenId: bigint, modelRootHash: string];
  export interface OutputObject {
    tokenId: bigint;
    modelRootHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TraitsUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageAuthorizedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    executor: AddressLike,
    permissions: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    executor: string,
    permissions: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    executor: string;
    permissions: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageRevokedEvent {
  export type InputTuple = [tokenId: BigNumberish, executor: AddressLike];
  export type OutputTuple = [tokenId: bigint, executor: string];
  export interface OutputObject {
    tokenId: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIArenaINFT extends BaseContract {
  connect(runner?: ContractRunner | null): AIArenaINFT;
  waitForDeployment(): Promise<this>;

  interface: AIArenaINFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CLONES: TypedContractMethod<[], [bigint], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  agentIdToTokenId: TypedContractMethod<[arg0: string], [bigint], "view">;

  agentMetadata: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        AIArenaINFT.AgentTraitsStructOutput
      ] & {
        agentId: string;
        clan: string;
        archetype: string;
        evolutionStage: bigint;
        wins: bigint;
        losses: bigint;
        draws: bigint;
        totalBattles: bigint;
        memoryRootHash: string;
        modelRootHash: string;
        genesisRootHash: string;
        encryptedMetadataHash: string;
        sealedKey: string;
        mintedAt: bigint;
        lastEvolvedAt: bigint;
        lastBattleAt: bigint;
        lastTrainingAt: bigint;
        traits: AIArenaINFT.AgentTraitsStructOutput;
      }
    ],
    "view"
  >;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorisedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizeUsage: TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike, permissions: BytesLike],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  clone: TypedContractMethod<
    [
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  cloneCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  cloneParent: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  evolveAgent: TypedContractMethod<
    [
      tokenId: BigNumberish,
      newTraits: AIArenaINFT.AgentTraitsStruct,
      newTokenUri: string
    ],
    [void],
    "nonpayable"
  >;

  getAgentByAgentId: TypedContractMethod<
    [agentId: string],
    [[AIArenaINFT.AgentMetadataStructOutput, bigint] & { tokenId: bigint }],
    "view"
  >;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getEvolutionStage: TypedContractMethod<
    [tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getTraits: TypedContractMethod<
    [tokenId: BigNumberish],
    [AIArenaINFT.AgentTraitsStructOutput],
    "view"
  >;

  hasValidUsage: TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mintAgent: TypedContractMethod<
    [
      to: AddressLike,
      agentId: string,
      clan: string,
      archetype: string,
      traits: AIArenaINFT.AgentTraitsStruct,
      encryptedMetadataHash: BytesLike,
      sealedKey: BytesLike,
      genesisRootHash: string,
      tokenUri: string
    ],
    [bigint],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  recordBattleResult: TypedContractMethod<
    [tokenId: BigNumberish, won: boolean, draw: boolean],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeUsage: TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEncryptedMetadata: TypedContractMethod<
    [tokenId: BigNumberish, newEncryptedMetadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateMemoryRoot: TypedContractMethod<
    [tokenId: BigNumberish, memoryRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  updateModelVersion: TypedContractMethod<
    [
      tokenId: BigNumberish,
      modelRootHash: string,
      newEncryptedMetadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  usagePermissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, string, boolean] & {
        executor: string;
        expiresAt: bigint;
        scopeHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CLONES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentIdToTokenId"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentMetadata"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        AIArenaINFT.AgentTraitsStructOutput
      ] & {
        agentId: string;
        clan: string;
        archetype: string;
        evolutionStage: bigint;
        wins: bigint;
        losses: bigint;
        draws: bigint;
        totalBattles: bigint;
        memoryRootHash: string;
        modelRootHash: string;
        genesisRootHash: string;
        encryptedMetadataHash: string;
        sealedKey: string;
        mintedAt: bigint;
        lastEvolvedAt: bigint;
        lastBattleAt: bigint;
        lastTrainingAt: bigint;
        traits: AIArenaINFT.AgentTraitsStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorisedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizeUsage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike, permissions: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "clone"
  ): TypedContractMethod<
    [
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cloneCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cloneParent"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "evolveAgent"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      newTraits: AIArenaINFT.AgentTraitsStruct,
      newTokenUri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentByAgentId"
  ): TypedContractMethod<
    [agentId: string],
    [[AIArenaINFT.AgentMetadataStructOutput, bigint] & { tokenId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEvolutionStage"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTraits"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [AIArenaINFT.AgentTraitsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasValidUsage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintAgent"
  ): TypedContractMethod<
    [
      to: AddressLike,
      agentId: string,
      clan: string,
      archetype: string,
      traits: AIArenaINFT.AgentTraitsStruct,
      encryptedMetadataHash: BytesLike,
      sealedKey: BytesLike,
      genesisRootHash: string,
      tokenUri: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordBattleResult"
  ): TypedContractMethod<
    [tokenId: BigNumberish, won: boolean, draw: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeUsage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, authorised: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEncryptedMetadata"
  ): TypedContractMethod<
    [tokenId: BigNumberish, newEncryptedMetadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMemoryRoot"
  ): TypedContractMethod<
    [tokenId: BigNumberish, memoryRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateModelVersion"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      modelRootHash: string,
      newEncryptedMetadataHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usagePermissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, string, boolean] & {
        executor: string;
        expiresAt: bigint;
        scopeHash: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AgentCloned"
  ): TypedContractEvent<
    AgentClonedEvent.InputTuple,
    AgentClonedEvent.OutputTuple,
    AgentClonedEvent.OutputObject
  >;
  getEvent(
    key: "AgentEvolved"
  ): TypedContractEvent<
    AgentEvolvedEvent.InputTuple,
    AgentEvolvedEvent.OutputTuple,
    AgentEvolvedEvent.OutputObject
  >;
  getEvent(
    key: "AgentMinted"
  ): TypedContractEvent<
    AgentMintedEvent.InputTuple,
    AgentMintedEvent.OutputTuple,
    AgentMintedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "BattleResultRecorded"
  ): TypedContractEvent<
    BattleResultRecordedEvent.InputTuple,
    BattleResultRecordedEvent.OutputTuple,
    BattleResultRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MemoryRootUpdated"
  ): TypedContractEvent<
    MemoryRootUpdatedEvent.InputTuple,
    MemoryRootUpdatedEvent.OutputTuple,
    MemoryRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ModelVersionUpdated"
  ): TypedContractEvent<
    ModelVersionUpdatedEvent.InputTuple,
    ModelVersionUpdatedEvent.OutputTuple,
    ModelVersionUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TraitsUpdated"
  ): TypedContractEvent<
    TraitsUpdatedEvent.InputTuple,
    TraitsUpdatedEvent.OutputTuple,
    TraitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UsageAuthorized"
  ): TypedContractEvent<
    UsageAuthorizedEvent.InputTuple,
    UsageAuthorizedEvent.OutputTuple,
    UsageAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "UsageRevoked"
  ): TypedContractEvent<
    UsageRevokedEvent.InputTuple,
    UsageRevokedEvent.OutputTuple,
    UsageRevokedEvent.OutputObject
  >;

  filters: {
    "AgentCloned(uint256,uint256,address)": TypedContractEvent<
      AgentClonedEvent.InputTuple,
      AgentClonedEvent.OutputTuple,
      AgentClonedEvent.OutputObject
    >;
    AgentCloned: TypedContractEvent<
      AgentClonedEvent.InputTuple,
      AgentClonedEvent.OutputTuple,
      AgentClonedEvent.OutputObject
    >;

    "AgentEvolved(uint256,uint8,uint8)": TypedContractEvent<
      AgentEvolvedEvent.InputTuple,
      AgentEvolvedEvent.OutputTuple,
      AgentEvolvedEvent.OutputObject
    >;
    AgentEvolved: TypedContractEvent<
      AgentEvolvedEvent.InputTuple,
      AgentEvolvedEvent.OutputTuple,
      AgentEvolvedEvent.OutputObject
    >;

    "AgentMinted(uint256,string,address,string)": TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;
    AgentMinted: TypedContractEvent<
      AgentMintedEvent.InputTuple,
      AgentMintedEvent.OutputTuple,
      AgentMintedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "BattleResultRecorded(uint256,bool,uint32)": TypedContractEvent<
      BattleResultRecordedEvent.InputTuple,
      BattleResultRecordedEvent.OutputTuple,
      BattleResultRecordedEvent.OutputObject
    >;
    BattleResultRecorded: TypedContractEvent<
      BattleResultRecordedEvent.InputTuple,
      BattleResultRecordedEvent.OutputTuple,
      BattleResultRecordedEvent.OutputObject
    >;

    "MemoryRootUpdated(uint256,bytes32)": TypedContractEvent<
      MemoryRootUpdatedEvent.InputTuple,
      MemoryRootUpdatedEvent.OutputTuple,
      MemoryRootUpdatedEvent.OutputObject
    >;
    MemoryRootUpdated: TypedContractEvent<
      MemoryRootUpdatedEvent.InputTuple,
      MemoryRootUpdatedEvent.OutputTuple,
      MemoryRootUpdatedEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "MetadataUpdated(uint256,bytes32)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;

    "ModelVersionUpdated(uint256,string)": TypedContractEvent<
      ModelVersionUpdatedEvent.InputTuple,
      ModelVersionUpdatedEvent.OutputTuple,
      ModelVersionUpdatedEvent.OutputObject
    >;
    ModelVersionUpdated: TypedContractEvent<
      ModelVersionUpdatedEvent.InputTuple,
      ModelVersionUpdatedEvent.OutputTuple,
      ModelVersionUpdatedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TraitsUpdated(uint256)": TypedContractEvent<
      TraitsUpdatedEvent.InputTuple,
      TraitsUpdatedEvent.OutputTuple,
      TraitsUpdatedEvent.OutputObject
    >;
    TraitsUpdated: TypedContractEvent<
      TraitsUpdatedEvent.InputTuple,
      TraitsUpdatedEvent.OutputTuple,
      TraitsUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UsageAuthorized(uint256,address,bytes)": TypedContractEvent<
      UsageAuthorizedEvent.InputTuple,
      UsageAuthorizedEvent.OutputTuple,
      UsageAuthorizedEvent.OutputObject
    >;
    UsageAuthorized: TypedContractEvent<
      UsageAuthorizedEvent.InputTuple,
      UsageAuthorizedEvent.OutputTuple,
      UsageAuthorizedEvent.OutputObject
    >;

    "UsageRevoked(uint256,address)": TypedContractEvent<
      UsageRevokedEvent.InputTuple,
      UsageRevokedEvent.OutputTuple,
      UsageRevokedEvent.OutputObject
    >;
    UsageRevoked: TypedContractEvent<
      UsageRevokedEvent.InputTuple,
      UsageRevokedEvent.OutputTuple,
      UsageRevokedEvent.OutputObject
    >;
  };
}
