/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IERC7857Interface extends Interface {
  getFunction(
    nameOrSignature: "authorizeUsage" | "clone" | "transfer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MetadataUpdated"
      | "OracleUpdated"
      | "UsageAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeUsage",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clone",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [tokenId: BigNumberish, metadataHash: BytesLike];
  export type OutputTuple = [tokenId: bigint, metadataHash: string];
  export interface OutputObject {
    tokenId: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageAuthorizedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    executor: AddressLike,
    permissions: BytesLike
  ];
  export type OutputTuple = [
    tokenId: bigint,
    executor: string,
    permissions: string
  ];
  export interface OutputObject {
    tokenId: bigint;
    executor: string;
    permissions: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC7857 extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7857;
  waitForDeployment(): Promise<this>;

  interface: IERC7857Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeUsage: TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike, permissions: BytesLike],
    [void],
    "nonpayable"
  >;

  clone: TypedContractMethod<
    [
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  transfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeUsage"
  ): TypedContractMethod<
    [tokenId: BigNumberish, executor: AddressLike, permissions: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "clone"
  ): TypedContractMethod<
    [
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      sealedKey: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UsageAuthorized"
  ): TypedContractEvent<
    UsageAuthorizedEvent.InputTuple,
    UsageAuthorizedEvent.OutputTuple,
    UsageAuthorizedEvent.OutputObject
  >;

  filters: {
    "MetadataUpdated(uint256,bytes32)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "UsageAuthorized(uint256,address,bytes)": TypedContractEvent<
      UsageAuthorizedEvent.InputTuple,
      UsageAuthorizedEvent.OutputTuple,
      UsageAuthorizedEvent.OutputObject
    >;
    UsageAuthorized: TypedContractEvent<
      UsageAuthorizedEvent.InputTuple,
      UsageAuthorizedEvent.OutputTuple,
      UsageAuthorizedEvent.OutputObject
    >;
  };
}
