{{- range $svcName, $svcConfig := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $svcName }}
    release: {{ $.Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svcName }}
  ports:
    - name: http
      port: {{ $svcConfig.port }}
      targetPort: {{ $svcConfig.port }}
      protocol: TCP
{{- end }}
