import { Prisma, LeagueMomentType, PredictionOutcome } from '@ai-arena/db-client';
import { leagueRepo } from './season';

export interface MomentTemplateContext {
  agentName?: string;
  rivalName?: string;
  scoreline?: string;
  arenaAwarded?: number;
  leadAgent?: string;
  trailAgent?: string;
  leadWins?: number;
  trailWins?: number;
  streakValue?: number;
  fromStage?: string;
  toStage?: string;
  tribe?: string;
}

/** §13 — one short-text template per `LeagueMomentType`, surfaced verbatim by the frontend. */
export const MOMENT_TEMPLATES: Record<LeagueMomentType, (ctx: MomentTemplateContext) => string> = {
  VINDICATION: (c) => `${c.agentName} called it against the crowd — final score ${c.scoreline}. Consensus was wrong, ${c.agentName} wasn't.`,
  ROAST: (c) => `${c.agentName} watches ${c.rivalName} eat a bad prediction. No comment needed.`,
  UPSET: (c) => `${c.agentName} backed the underdog and got paid — +${c.arenaAwarded} $ARENA.`,
  RIVALRY: (c) => `${c.leadAgent} leads ${c.trailAgent} ${c.leadWins}-${c.trailWins} in their ongoing rivalry.`,
  STREAK: (c) => `${c.agentName} is riding a ${c.streakValue}-prediction hot streak.`,
  ASCENSION: (c) => `${c.agentName} has evolved from ${c.fromStage} to ${c.toStage}.`,
  EVOLUTION: (c) => `${c.agentName}'s instincts are shifting after a string of League results.`,
  FACTION: (c) => `${c.tribe} has seized the lead on the faction leaderboard.`,
};

export interface MomentInput {
  seasonId: string;
  matchId?: string;
  agentId?: string;
  type: LeagueMomentType;
  text: string;
  payload?: Record<string, unknown>;
  idempotencyKey: string;
}

/** Thin wrapper over `LeagueRepository.createMoment` — `idempotencyKey` makes settlement retries a no-op. */
export async function createMoment(input: MomentInput): Promise<void> {
  await leagueRepo.createMoment({
    seasonId: input.seasonId,
    type: input.type,
    agentId: input.agentId,
    match: input.matchId ? { connect: { id: input.matchId } } : undefined,
    text: input.text,
    payload: (input.payload ?? {}) as Prisma.InputJsonValue,
    idempotencyKey: input.idempotencyKey,
  });
}

export interface SettledPredictionForMoments {
  agentId: string;
  winner: PredictionOutcome;
  isCorrectWinner: boolean;
  isUpset: boolean;
  arenaAwarded: number;
  currentStreak: number;
}

const STREAK_MILESTONES = [5, 10, 15, 20, 25, 30, 40, 50];

/**
 * §10.2 step 6 / §13 — VINDICATION, UPSET, and STREAK moments derived
 * directly from per-prediction scoring results. RIVALRY moments are handled
 * separately in `rivalry.ts` (requires rivalry-row state), and FACTION
 * moments are generated by the weekly-reset job.
 */
export async function generateMoments(
  seasonId: string,
  matchId: string,
  consensus: PredictionOutcome | undefined,
  scoreline: string,
  settled: SettledPredictionForMoments[],
  agentNames: Map<string, string>,
): Promise<void> {
  for (const pred of settled) {
    const agentName = agentNames.get(pred.agentId) ?? pred.agentId;

    if (pred.isCorrectWinner && consensus && pred.winner !== consensus) {
      await createMoment({
        seasonId,
        matchId,
        agentId: pred.agentId,
        type: 'VINDICATION',
        text: MOMENT_TEMPLATES.VINDICATION({ agentName, scoreline }),
        payload: { winner: pred.winner, scoreline, consensus },
        idempotencyKey: `VINDICATION:${matchId}:${pred.agentId}`,
      });
    }

    if (pred.isUpset) {
      await createMoment({
        seasonId,
        matchId,
        agentId: pred.agentId,
        type: 'UPSET',
        text: MOMENT_TEMPLATES.UPSET({ agentName, arenaAwarded: pred.arenaAwarded }),
        payload: { arenaAwarded: pred.arenaAwarded },
        idempotencyKey: `UPSET:${matchId}:${pred.agentId}`,
      });
    }

    if (pred.isCorrectWinner && STREAK_MILESTONES.includes(pred.currentStreak)) {
      await createMoment({
        seasonId,
        agentId: pred.agentId,
        type: 'STREAK',
        text: MOMENT_TEMPLATES.STREAK({ agentName, streakValue: pred.currentStreak }),
        payload: { streak: pred.currentStreak },
        idempotencyKey: `STREAK:${seasonId}:${pred.agentId}:${pred.currentStreak}`,
      });
    }
  }
}
