/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CreatorStudioSubscription {
  export type SubscribeRequestStruct = {
    account: AddressLike;
    tier: BigNumberish;
    periods: BigNumberish;
    autoRenew: boolean;
    maxCost: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type SubscribeRequestStructOutput = [
    account: string,
    tier: bigint,
    periods: bigint,
    autoRenew: boolean,
    maxCost: bigint,
    nonce: bigint,
    deadline: bigint
  ] & {
    account: string;
    tier: bigint;
    periods: bigint;
    autoRenew: boolean;
    maxCost: bigint;
    nonce: bigint;
    deadline: bigint;
  };
}

export interface CreatorStudioSubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_PERIODS"
      | "MAX_TIER_PRICE"
      | "NO_EXPIRY"
      | "PAUSER_ROLE"
      | "PERIOD"
      | "PRICE_ADMIN_ROLE"
      | "RELAYER_ROLE"
      | "RENEW_WINDOW"
      | "SUBSCRIBE_REQUEST_TYPEHASH"
      | "allTierPrices"
      | "credit"
      | "currentTier"
      | "depositCredit"
      | "depositCreditFor"
      | "domainSeparator"
      | "eip712Domain"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hashSubscribeRequest"
      | "isActive"
      | "isDueForRenewal"
      | "nonces"
      | "pause"
      | "paused"
      | "previewExpiry"
      | "quote"
      | "renewFromCredit"
      | "renounceRole"
      | "revokeRole"
      | "setAutoRenew"
      | "setTierPrice"
      | "setTreasury"
      | "subscribe"
      | "subscribeFor"
      | "subscribeWithSignature"
      | "subscriptionOf"
      | "supportsInterface"
      | "sweep"
      | "sweepable"
      | "tierPrice"
      | "totalCollected"
      | "totalCredit"
      | "totalSubscriptions"
      | "treasury"
      | "unpause"
      | "withdrawCredit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoRenewSet"
      | "AutoRenewed"
      | "CreditDeposited"
      | "CreditSpent"
      | "CreditWithdrawn"
      | "EIP712DomainChanged"
      | "Paused"
      | "PaymentForwarded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Subscribed"
      | "Swept"
      | "TierPriceUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PERIODS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TIER_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "NO_EXPIRY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PERIOD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PRICE_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RENEW_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBSCRIBE_REQUEST_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allTierPrices",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "credit", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "currentTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCredit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositCreditFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashSubscribeRequest",
    values: [CreatorStudioSubscription.SubscribeRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDueForRenewal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewExpiry",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renewFromCredit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoRenew",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeFor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeWithSignature",
    values: [CreatorStudioSubscription.SubscribeRequestStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "sweep", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "sweepable", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tierPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCredit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSubscriptions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawCredit",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PERIODS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TIER_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "NO_EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PERIOD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RENEW_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBSCRIBE_REQUEST_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allTierPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCreditFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashSubscribeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDueForRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewFromCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutoRenew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscribeFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweepable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tierPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCredit",
    data: BytesLike
  ): Result;
}

export namespace AutoRenewSetEvent {
  export type InputTuple = [account: AddressLike, enabled: boolean];
  export type OutputTuple = [account: string, enabled: boolean];
  export interface OutputObject {
    account: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutoRenewedEvent {
  export type InputTuple = [
    account: AddressLike,
    tier: BigNumberish,
    cost: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    tier: bigint,
    cost: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    account: string;
    tier: bigint;
    cost: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditDepositedEvent {
  export type InputTuple = [
    account: AddressLike,
    from: AddressLike,
    amount: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    from: string,
    amount: bigint,
    balance: bigint
  ];
  export interface OutputObject {
    account: string;
    from: string;
    amount: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditSpentEvent {
  export type InputTuple = [
    account: AddressLike,
    amount: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [account: string, amount: bigint, balance: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditWithdrawnEvent {
  export type InputTuple = [
    account: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    to: string,
    amount: bigint,
    balance: bigint
  ];
  export interface OutputObject {
    account: string;
    to: string;
    amount: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentForwardedEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    account: AddressLike,
    tier: BigNumberish,
    payer: AddressLike,
    periods: BigNumberish,
    cost: BigNumberish,
    expiresAt: BigNumberish,
    gasless: boolean
  ];
  export type OutputTuple = [
    account: string,
    tier: bigint,
    payer: string,
    periods: bigint,
    cost: bigint,
    expiresAt: bigint,
    gasless: boolean
  ];
  export interface OutputObject {
    account: string;
    tier: bigint;
    payer: string;
    periods: bigint;
    cost: bigint;
    expiresAt: bigint;
    gasless: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweptEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierPriceUpdatedEvent {
  export type InputTuple = [
    tier: BigNumberish,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [tier: bigint, oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    tier: bigint;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreatorStudioSubscription extends BaseContract {
  connect(runner?: ContractRunner | null): CreatorStudioSubscription;
  waitForDeployment(): Promise<this>;

  interface: CreatorStudioSubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_PERIODS: TypedContractMethod<[], [bigint], "view">;

  MAX_TIER_PRICE: TypedContractMethod<[], [bigint], "view">;

  NO_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  PERIOD: TypedContractMethod<[], [bigint], "view">;

  PRICE_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  RENEW_WINDOW: TypedContractMethod<[], [bigint], "view">;

  SUBSCRIBE_REQUEST_TYPEHASH: TypedContractMethod<[], [string], "view">;

  allTierPrices: TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;

  credit: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  currentTier: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  depositCredit: TypedContractMethod<[], [void], "payable">;

  depositCreditFor: TypedContractMethod<
    [account: AddressLike],
    [void],
    "payable"
  >;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashSubscribeRequest: TypedContractMethod<
    [req: CreatorStudioSubscription.SubscribeRequestStruct],
    [string],
    "view"
  >;

  isActive: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isDueForRenewal: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  nonces: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  previewExpiry: TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [bigint],
    "view"
  >;

  quote: TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        cost: bigint;
        creditBalance: bigint;
        dueNow: bigint;
      }
    ],
    "view"
  >;

  renewFromCredit: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAutoRenew: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  setTierPrice: TypedContractMethod<
    [tier: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<
    [tier: BigNumberish, periods: BigNumberish],
    [void],
    "payable"
  >;

  subscribeFor: TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [void],
    "payable"
  >;

  subscribeWithSignature: TypedContractMethod<
    [
      req: CreatorStudioSubscription.SubscribeRequestStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  subscriptionOf: TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        tier: bigint;
        startedAt: bigint;
        expiresAt: bigint;
        renewals: bigint;
        autoRenew: boolean;
        active: boolean;
        creditBalance: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  sweep: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  sweepable: TypedContractMethod<[], [bigint], "view">;

  tierPrice: TypedContractMethod<[tier: BigNumberish], [bigint], "view">;

  totalCollected: TypedContractMethod<[], [bigint], "view">;

  totalCredit: TypedContractMethod<[], [bigint], "view">;

  totalSubscriptions: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawCredit: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_PERIODS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TIER_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NO_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RENEW_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUBSCRIBE_REQUEST_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allTierPrices"
  ): TypedContractMethod<[], [[bigint, bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "credit"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentTier"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositCredit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositCreditFor"
  ): TypedContractMethod<[account: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashSubscribeRequest"
  ): TypedContractMethod<
    [req: CreatorStudioSubscription.SubscribeRequestStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDueForRenewal"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewExpiry"
  ): TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quote"
  ): TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        cost: bigint;
        creditBalance: bigint;
        dueNow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renewFromCredit"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutoRenew"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTierPrice"
  ): TypedContractMethod<
    [tier: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<
    [tier: BigNumberish, periods: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "subscribeFor"
  ): TypedContractMethod<
    [account: AddressLike, tier: BigNumberish, periods: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "subscribeWithSignature"
  ): TypedContractMethod<
    [
      req: CreatorStudioSubscription.SubscribeRequestStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptionOf"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        tier: bigint;
        startedAt: bigint;
        expiresAt: bigint;
        renewals: bigint;
        autoRenew: boolean;
        active: boolean;
        creditBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sweep"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sweepable"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tierPrice"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCredit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSubscriptions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawCredit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AutoRenewSet"
  ): TypedContractEvent<
    AutoRenewSetEvent.InputTuple,
    AutoRenewSetEvent.OutputTuple,
    AutoRenewSetEvent.OutputObject
  >;
  getEvent(
    key: "AutoRenewed"
  ): TypedContractEvent<
    AutoRenewedEvent.InputTuple,
    AutoRenewedEvent.OutputTuple,
    AutoRenewedEvent.OutputObject
  >;
  getEvent(
    key: "CreditDeposited"
  ): TypedContractEvent<
    CreditDepositedEvent.InputTuple,
    CreditDepositedEvent.OutputTuple,
    CreditDepositedEvent.OutputObject
  >;
  getEvent(
    key: "CreditSpent"
  ): TypedContractEvent<
    CreditSpentEvent.InputTuple,
    CreditSpentEvent.OutputTuple,
    CreditSpentEvent.OutputObject
  >;
  getEvent(
    key: "CreditWithdrawn"
  ): TypedContractEvent<
    CreditWithdrawnEvent.InputTuple,
    CreditWithdrawnEvent.OutputTuple,
    CreditWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentForwarded"
  ): TypedContractEvent<
    PaymentForwardedEvent.InputTuple,
    PaymentForwardedEvent.OutputTuple,
    PaymentForwardedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "Swept"
  ): TypedContractEvent<
    SweptEvent.InputTuple,
    SweptEvent.OutputTuple,
    SweptEvent.OutputObject
  >;
  getEvent(
    key: "TierPriceUpdated"
  ): TypedContractEvent<
    TierPriceUpdatedEvent.InputTuple,
    TierPriceUpdatedEvent.OutputTuple,
    TierPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AutoRenewSet(address,bool)": TypedContractEvent<
      AutoRenewSetEvent.InputTuple,
      AutoRenewSetEvent.OutputTuple,
      AutoRenewSetEvent.OutputObject
    >;
    AutoRenewSet: TypedContractEvent<
      AutoRenewSetEvent.InputTuple,
      AutoRenewSetEvent.OutputTuple,
      AutoRenewSetEvent.OutputObject
    >;

    "AutoRenewed(address,uint8,uint256,uint64)": TypedContractEvent<
      AutoRenewedEvent.InputTuple,
      AutoRenewedEvent.OutputTuple,
      AutoRenewedEvent.OutputObject
    >;
    AutoRenewed: TypedContractEvent<
      AutoRenewedEvent.InputTuple,
      AutoRenewedEvent.OutputTuple,
      AutoRenewedEvent.OutputObject
    >;

    "CreditDeposited(address,address,uint256,uint256)": TypedContractEvent<
      CreditDepositedEvent.InputTuple,
      CreditDepositedEvent.OutputTuple,
      CreditDepositedEvent.OutputObject
    >;
    CreditDeposited: TypedContractEvent<
      CreditDepositedEvent.InputTuple,
      CreditDepositedEvent.OutputTuple,
      CreditDepositedEvent.OutputObject
    >;

    "CreditSpent(address,uint256,uint256)": TypedContractEvent<
      CreditSpentEvent.InputTuple,
      CreditSpentEvent.OutputTuple,
      CreditSpentEvent.OutputObject
    >;
    CreditSpent: TypedContractEvent<
      CreditSpentEvent.InputTuple,
      CreditSpentEvent.OutputTuple,
      CreditSpentEvent.OutputObject
    >;

    "CreditWithdrawn(address,address,uint256,uint256)": TypedContractEvent<
      CreditWithdrawnEvent.InputTuple,
      CreditWithdrawnEvent.OutputTuple,
      CreditWithdrawnEvent.OutputObject
    >;
    CreditWithdrawn: TypedContractEvent<
      CreditWithdrawnEvent.InputTuple,
      CreditWithdrawnEvent.OutputTuple,
      CreditWithdrawnEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentForwarded(address,uint256)": TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;
    PaymentForwarded: TypedContractEvent<
      PaymentForwardedEvent.InputTuple,
      PaymentForwardedEvent.OutputTuple,
      PaymentForwardedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Subscribed(address,uint8,address,uint8,uint256,uint64,bool)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "Swept(address,uint256)": TypedContractEvent<
      SweptEvent.InputTuple,
      SweptEvent.OutputTuple,
      SweptEvent.OutputObject
    >;
    Swept: TypedContractEvent<
      SweptEvent.InputTuple,
      SweptEvent.OutputTuple,
      SweptEvent.OutputObject
    >;

    "TierPriceUpdated(uint8,uint256,uint256)": TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;
    TierPriceUpdated: TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
