/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ArenaTournamentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_COMMISSION_BPS"
      | "RELAYER_ROLE"
      | "arenaToken"
      | "cancelTournament"
      | "commissionBps"
      | "createTournament"
      | "enterTournament"
      | "getParticipants"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isEntrant"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "setCommissionBps"
      | "settleTournament"
      | "startTournament"
      | "supportsInterface"
      | "tournaments"
      | "treasury"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommissionBpsUpdated"
      | "CommissionCollected"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TournamentCancelled"
      | "TournamentCreated"
      | "TournamentEntered"
      | "TournamentRewardGranted"
      | "TournamentStarted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COMMISSION_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "arenaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commissionBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTournament",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enterTournament",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEntrant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommissionBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleTournament",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "startTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tournaments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COMMISSION_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arenaToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commissionBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEntrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommissionBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournaments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace CommissionBpsUpdatedEvent {
  export type InputTuple = [newBps: BigNumberish];
  export type OutputTuple = [newBps: bigint];
  export interface OutputObject {
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommissionCollectedEvent {
  export type InputTuple = [tournamentId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [tournamentId: bigint, amount: bigint];
  export interface OutputObject {
    tournamentId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCancelledEvent {
  export type InputTuple = [tournamentId: BigNumberish];
  export type OutputTuple = [tournamentId: bigint];
  export interface OutputObject {
    tournamentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentCreatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    entryFee: BigNumberish,
    maxParticipants: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    entryFee: bigint,
    maxParticipants: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    entryFee: bigint;
    maxParticipants: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentEnteredEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    player: AddressLike,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    player: string,
    participantCount: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentRewardGrantedEvent {
  export type InputTuple = [
    player: AddressLike,
    tournamentId: BigNumberish,
    rank: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    tournamentId: bigint,
    rank: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    player: string;
    tournamentId: bigint;
    rank: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentStartedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [tournamentId: bigint, participantCount: bigint];
  export interface OutputObject {
    tournamentId: bigint;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArenaTournament extends BaseContract {
  connect(runner?: ContractRunner | null): ArenaTournament;
  waitForDeployment(): Promise<this>;

  interface: ArenaTournamentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_COMMISSION_BPS: TypedContractMethod<[], [bigint], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  arenaToken: TypedContractMethod<[], [string], "view">;

  cancelTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  commissionBps: TypedContractMethod<[], [bigint], "view">;

  createTournament: TypedContractMethod<
    [
      tournamentId: BigNumberish,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  enterTournament: TypedContractMethod<
    [tournamentId: BigNumberish, player: AddressLike],
    [void],
    "nonpayable"
  >;

  getParticipants: TypedContractMethod<
    [tournamentId: BigNumberish],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isEntrant: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setCommissionBps: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleTournament: TypedContractMethod<
    [
      tournamentId: BigNumberish,
      winners: AddressLike[],
      prizeBps: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  startTournament: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tournaments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        entryFee: bigint;
        maxParticipants: bigint;
        state: bigint;
        commissionBpsAtCreation: bigint;
      }
    ],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_COMMISSION_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "arenaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commissionBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createTournament"
  ): TypedContractMethod<
    [
      tournamentId: BigNumberish,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterTournament"
  ): TypedContractMethod<
    [tournamentId: BigNumberish, player: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<[tournamentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEntrant"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCommissionBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleTournament"
  ): TypedContractMethod<
    [
      tournamentId: BigNumberish,
      winners: AddressLike[],
      prizeBps: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startTournament"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tournaments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        entryFee: bigint;
        maxParticipants: bigint;
        state: bigint;
        commissionBpsAtCreation: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CommissionBpsUpdated"
  ): TypedContractEvent<
    CommissionBpsUpdatedEvent.InputTuple,
    CommissionBpsUpdatedEvent.OutputTuple,
    CommissionBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CommissionCollected"
  ): TypedContractEvent<
    CommissionCollectedEvent.InputTuple,
    CommissionCollectedEvent.OutputTuple,
    CommissionCollectedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCancelled"
  ): TypedContractEvent<
    TournamentCancelledEvent.InputTuple,
    TournamentCancelledEvent.OutputTuple,
    TournamentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TournamentCreated"
  ): TypedContractEvent<
    TournamentCreatedEvent.InputTuple,
    TournamentCreatedEvent.OutputTuple,
    TournamentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentEntered"
  ): TypedContractEvent<
    TournamentEnteredEvent.InputTuple,
    TournamentEnteredEvent.OutputTuple,
    TournamentEnteredEvent.OutputObject
  >;
  getEvent(
    key: "TournamentRewardGranted"
  ): TypedContractEvent<
    TournamentRewardGrantedEvent.InputTuple,
    TournamentRewardGrantedEvent.OutputTuple,
    TournamentRewardGrantedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentStarted"
  ): TypedContractEvent<
    TournamentStartedEvent.InputTuple,
    TournamentStartedEvent.OutputTuple,
    TournamentStartedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CommissionBpsUpdated(uint256)": TypedContractEvent<
      CommissionBpsUpdatedEvent.InputTuple,
      CommissionBpsUpdatedEvent.OutputTuple,
      CommissionBpsUpdatedEvent.OutputObject
    >;
    CommissionBpsUpdated: TypedContractEvent<
      CommissionBpsUpdatedEvent.InputTuple,
      CommissionBpsUpdatedEvent.OutputTuple,
      CommissionBpsUpdatedEvent.OutputObject
    >;

    "CommissionCollected(uint256,uint256)": TypedContractEvent<
      CommissionCollectedEvent.InputTuple,
      CommissionCollectedEvent.OutputTuple,
      CommissionCollectedEvent.OutputObject
    >;
    CommissionCollected: TypedContractEvent<
      CommissionCollectedEvent.InputTuple,
      CommissionCollectedEvent.OutputTuple,
      CommissionCollectedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TournamentCancelled(uint256)": TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;
    TournamentCancelled: TypedContractEvent<
      TournamentCancelledEvent.InputTuple,
      TournamentCancelledEvent.OutputTuple,
      TournamentCancelledEvent.OutputObject
    >;

    "TournamentCreated(uint256,uint256,uint256)": TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;
    TournamentCreated: TypedContractEvent<
      TournamentCreatedEvent.InputTuple,
      TournamentCreatedEvent.OutputTuple,
      TournamentCreatedEvent.OutputObject
    >;

    "TournamentEntered(uint256,address,uint256)": TypedContractEvent<
      TournamentEnteredEvent.InputTuple,
      TournamentEnteredEvent.OutputTuple,
      TournamentEnteredEvent.OutputObject
    >;
    TournamentEntered: TypedContractEvent<
      TournamentEnteredEvent.InputTuple,
      TournamentEnteredEvent.OutputTuple,
      TournamentEnteredEvent.OutputObject
    >;

    "TournamentRewardGranted(address,uint256,uint256,uint256)": TypedContractEvent<
      TournamentRewardGrantedEvent.InputTuple,
      TournamentRewardGrantedEvent.OutputTuple,
      TournamentRewardGrantedEvent.OutputObject
    >;
    TournamentRewardGranted: TypedContractEvent<
      TournamentRewardGrantedEvent.InputTuple,
      TournamentRewardGrantedEvent.OutputTuple,
      TournamentRewardGrantedEvent.OutputObject
    >;

    "TournamentStarted(uint256,uint256)": TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;
    TournamentStarted: TypedContractEvent<
      TournamentStartedEvent.InputTuple,
      TournamentStartedEvent.OutputTuple,
      TournamentStartedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
