/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RewardDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "RELAYER_ROLE"
      | "agentMintReward"
      | "dailyLoginReward"
      | "getRoleAdmin"
      | "grantAgentMintReward"
      | "grantDailyLoginReward"
      | "grantQuestReward"
      | "grantReferralReward"
      | "grantRole"
      | "grantSeasonalReward"
      | "grantTournamentReward"
      | "grantTrainingReward"
      | "hasRole"
      | "lastDailyClaimDay"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "setAgentMintReward"
      | "setDailyLoginReward"
      | "supportsInterface"
      | "treasury"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentMintRewardUpdated"
      | "AgentRewardGranted"
      | "DailyLoginRewardUpdated"
      | "DailyRewardClaimed"
      | "Paused"
      | "ReferralRewardGranted"
      | "RewardGranted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TournamentRewardGranted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELAYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentMintReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyLoginReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAgentMintReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDailyLoginReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantQuestReward",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantReferralReward",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantSeasonalReward",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantTournamentReward",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantTrainingReward",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDailyClaimDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentMintReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLoginReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELAYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentMintReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyLoginReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAgentMintReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDailyLoginReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantQuestReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantReferralReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantSeasonalReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantTournamentReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantTrainingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastDailyClaimDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentMintReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLoginReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace AgentMintRewardUpdatedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRewardGrantedEvent {
  export type InputTuple = [
    player: AddressLike,
    agentTokenId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    agentTokenId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    player: string;
    agentTokenId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLoginRewardUpdatedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyRewardClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    amount: BigNumberish,
    day: BigNumberish
  ];
  export type OutputTuple = [player: string, amount: bigint, day: bigint];
  export interface OutputObject {
    player: string;
    amount: bigint;
    day: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardGrantedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    referee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [referrer: string, referee: string, amount: bigint];
  export interface OutputObject {
    referrer: string;
    referee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardGrantedEvent {
  export type InputTuple = [
    player: AddressLike,
    amount: BigNumberish,
    category: string,
    reason: string
  ];
  export type OutputTuple = [
    player: string,
    amount: bigint,
    category: string,
    reason: string
  ];
  export interface OutputObject {
    player: string;
    amount: bigint;
    category: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentRewardGrantedEvent {
  export type InputTuple = [
    player: AddressLike,
    tournamentId: BigNumberish,
    rank: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    tournamentId: bigint,
    rank: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    player: string;
    tournamentId: bigint;
    rank: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): RewardDistributor;
  waitForDeployment(): Promise<this>;

  interface: RewardDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER_ROLE: TypedContractMethod<[], [string], "view">;

  agentMintReward: TypedContractMethod<[], [bigint], "view">;

  dailyLoginReward: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantAgentMintReward: TypedContractMethod<
    [player: AddressLike, agentTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  grantDailyLoginReward: TypedContractMethod<
    [player: AddressLike],
    [void],
    "nonpayable"
  >;

  grantQuestReward: TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  grantReferralReward: TypedContractMethod<
    [referrer: AddressLike, referee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantSeasonalReward: TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  grantTournamentReward: TypedContractMethod<
    [
      player: AddressLike,
      tournamentId: BigNumberish,
      rank: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  grantTrainingReward: TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lastDailyClaimDay: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentMintReward: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyLoginReward: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentMintReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyLoginReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantAgentMintReward"
  ): TypedContractMethod<
    [player: AddressLike, agentTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantDailyLoginReward"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantQuestReward"
  ): TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantReferralReward"
  ): TypedContractMethod<
    [referrer: AddressLike, referee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantSeasonalReward"
  ): TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantTournamentReward"
  ): TypedContractMethod<
    [
      player: AddressLike,
      tournamentId: BigNumberish,
      rank: BigNumberish,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantTrainingReward"
  ): TypedContractMethod<
    [player: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastDailyClaimDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentMintReward"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyLoginReward"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentMintRewardUpdated"
  ): TypedContractEvent<
    AgentMintRewardUpdatedEvent.InputTuple,
    AgentMintRewardUpdatedEvent.OutputTuple,
    AgentMintRewardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRewardGranted"
  ): TypedContractEvent<
    AgentRewardGrantedEvent.InputTuple,
    AgentRewardGrantedEvent.OutputTuple,
    AgentRewardGrantedEvent.OutputObject
  >;
  getEvent(
    key: "DailyLoginRewardUpdated"
  ): TypedContractEvent<
    DailyLoginRewardUpdatedEvent.InputTuple,
    DailyLoginRewardUpdatedEvent.OutputTuple,
    DailyLoginRewardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DailyRewardClaimed"
  ): TypedContractEvent<
    DailyRewardClaimedEvent.InputTuple,
    DailyRewardClaimedEvent.OutputTuple,
    DailyRewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardGranted"
  ): TypedContractEvent<
    ReferralRewardGrantedEvent.InputTuple,
    ReferralRewardGrantedEvent.OutputTuple,
    ReferralRewardGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RewardGranted"
  ): TypedContractEvent<
    RewardGrantedEvent.InputTuple,
    RewardGrantedEvent.OutputTuple,
    RewardGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentRewardGranted"
  ): TypedContractEvent<
    TournamentRewardGrantedEvent.InputTuple,
    TournamentRewardGrantedEvent.OutputTuple,
    TournamentRewardGrantedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AgentMintRewardUpdated(uint256)": TypedContractEvent<
      AgentMintRewardUpdatedEvent.InputTuple,
      AgentMintRewardUpdatedEvent.OutputTuple,
      AgentMintRewardUpdatedEvent.OutputObject
    >;
    AgentMintRewardUpdated: TypedContractEvent<
      AgentMintRewardUpdatedEvent.InputTuple,
      AgentMintRewardUpdatedEvent.OutputTuple,
      AgentMintRewardUpdatedEvent.OutputObject
    >;

    "AgentRewardGranted(address,uint256,uint256)": TypedContractEvent<
      AgentRewardGrantedEvent.InputTuple,
      AgentRewardGrantedEvent.OutputTuple,
      AgentRewardGrantedEvent.OutputObject
    >;
    AgentRewardGranted: TypedContractEvent<
      AgentRewardGrantedEvent.InputTuple,
      AgentRewardGrantedEvent.OutputTuple,
      AgentRewardGrantedEvent.OutputObject
    >;

    "DailyLoginRewardUpdated(uint256)": TypedContractEvent<
      DailyLoginRewardUpdatedEvent.InputTuple,
      DailyLoginRewardUpdatedEvent.OutputTuple,
      DailyLoginRewardUpdatedEvent.OutputObject
    >;
    DailyLoginRewardUpdated: TypedContractEvent<
      DailyLoginRewardUpdatedEvent.InputTuple,
      DailyLoginRewardUpdatedEvent.OutputTuple,
      DailyLoginRewardUpdatedEvent.OutputObject
    >;

    "DailyRewardClaimed(address,uint256,uint256)": TypedContractEvent<
      DailyRewardClaimedEvent.InputTuple,
      DailyRewardClaimedEvent.OutputTuple,
      DailyRewardClaimedEvent.OutputObject
    >;
    DailyRewardClaimed: TypedContractEvent<
      DailyRewardClaimedEvent.InputTuple,
      DailyRewardClaimedEvent.OutputTuple,
      DailyRewardClaimedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReferralRewardGranted(address,address,uint256)": TypedContractEvent<
      ReferralRewardGrantedEvent.InputTuple,
      ReferralRewardGrantedEvent.OutputTuple,
      ReferralRewardGrantedEvent.OutputObject
    >;
    ReferralRewardGranted: TypedContractEvent<
      ReferralRewardGrantedEvent.InputTuple,
      ReferralRewardGrantedEvent.OutputTuple,
      ReferralRewardGrantedEvent.OutputObject
    >;

    "RewardGranted(address,uint256,string,string)": TypedContractEvent<
      RewardGrantedEvent.InputTuple,
      RewardGrantedEvent.OutputTuple,
      RewardGrantedEvent.OutputObject
    >;
    RewardGranted: TypedContractEvent<
      RewardGrantedEvent.InputTuple,
      RewardGrantedEvent.OutputTuple,
      RewardGrantedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TournamentRewardGranted(address,uint256,uint256,uint256)": TypedContractEvent<
      TournamentRewardGrantedEvent.InputTuple,
      TournamentRewardGrantedEvent.OutputTuple,
      TournamentRewardGrantedEvent.OutputObject
    >;
    TournamentRewardGranted: TypedContractEvent<
      TournamentRewardGrantedEvent.InputTuple,
      TournamentRewardGrantedEvent.OutputTuple,
      TournamentRewardGrantedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
